version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000" #first port is of host, second is of image
    volumes:
      - D:\\Users\\703219193\\Desktop\\practice-pro\\recipe-app-api\\app:/app #maps local app directory to docker image
    command: >
      sh -c "python manage.py wait_for_db &&
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=postgres

    depends_on:
      - db

  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres






#docker-compose build , will build Dockerfile using this configuration
#docker-compose run app sh -c "django-admin.py startproject app ." to run command inside image